# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_0_8_initial'),
        ('volumes', '0001_0_8_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='stack',
        ),
        migrations.AddField(
            model_name='volume',
            name='blueprint_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='blueprints.BlueprintVolume'),
        ),
    ]
