# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_0_8_0_a_migrations'),
        ('volumes', '0001_0_8_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='stack',
        ),
        migrations.AddField(
            model_name='volume',
            name='blueprint_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='blueprints.BlueprintVolume'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
