# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_0_8_0_migrations'),
        ('volumes', '0001_0_8_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='stack',
        ),
        # They are null at first, but we don't allow them to be null later after the values are populated
        migrations.AddField(
            model_name='volume',
            name='blueprint_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='blueprints.BlueprintVolume'),
        ),
        # Allow some other fields to be null for a bit (only matters for reverse)
        migrations.AlterField(
            model_name='volume',
            name='snapshot',
            field=models.ForeignKey(to='cloud.Snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='device',
            field=models.CharField(max_length=32, verbose_name='Device', null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='hostname',
            field=models.CharField(max_length=64, verbose_name='Hostname', null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='mount_point',
            field=models.CharField(max_length=255, verbose_name='Mount Point', null=True),
        ),
    ]
