# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0003_0_8_0_migrations'),
    ]

    operations = [
        # Make the blueprint_volumes non-nullable
        migrations.AlterField(
            model_name='volume',
            name='blueprint_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='blueprints.BlueprintVolume'),
        ),
        # Remove the fields we don't need anymore
        migrations.RemoveField(
            model_name='volume',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='device',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='mount_point',
        ),

        # Everything else that needs to be changed
        migrations.AlterField(
            model_name='volume',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='stacks.Host'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='attach_time',
        ),
    ]
