# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_0_8_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='availability_zone',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cloud_image',
        ),
        migrations.RemoveField(
            model_name='host',
            name='instance_size',
        ),
        migrations.RemoveField(
            model_name='host',
            name='subnet_id',
        ),
        migrations.AlterField(
            model_name='host',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='host',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=model_utils.fields.StatusField(default=b'pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=model_utils.fields.StatusField(default=b'pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stackcommand',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='stackcommand',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='stackcommand',
            name='status',
            field=model_utils.fields.StatusField(default=b'waiting', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stackhistory',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='stackhistory',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='stackhistory',
            name='status',
            field=model_utils.fields.StatusField(default=b'pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
