# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
"""
We need three stack migrations for 0.8.0 - there is an issue with fixing data and migrating
schema at the same time
"""

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_0_8_0_migrations'),
    ]

    operations = [
        # Delete all the fields
        migrations.RemoveField(
            model_name='host',
            name='availability_zone',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cloud_image',
        ),
        migrations.RemoveField(
            model_name='host',
            name='instance_size',
        ),
        migrations.RemoveField(
            model_name='host',
            name='subnet_id',
        ),
    ]
