# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 20:07
from __future__ import unicode_literals

import os
from django.db import migrations


def delete_top_files(apps, schema_migration):
    Stack = apps.get_model('stacks', 'Stack')

    # Delete all the top files.
    for stack in Stack.object.all():
        if os.path.exists(stack.top_file.path):
            os.remove(stack.top_file.path)


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_0_8_0_migrations'),
    ]

    operations = [
        migrations.RunPython(delete_top_files, lambda a, s: None),
        migrations.RemoveField(
            model_name='stack',
            name='top_file',
        ),
    ]
