# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 20:07
from __future__ import unicode_literals

import stackdio.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_0_8_0_migrations'),
    ]

    operations = [
        # Add the properties field first
        migrations.AddField(
            model_name='stack',
            name='properties',
            field=stackdio.core.fields.JSONField(verbose_name='Properties'),
        ),
    ]
