# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0006_0_8_0_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='top_file',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='global_orchestrate_file',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='global_pillar_file',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='map_file',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='orchestrate_file',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='pillar_file',
        ),
        # Then delete the props_file field after we loaded data from it in the previous migration
        migrations.RemoveField(
            model_name='stack',
            name='props_file',
        ),
    ]
