# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import stackdio.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
                ('properties', stackdio.core.fields.JSONField(verbose_name='Properties')),
            ],
            options={
                'ordering': ('title',),
                'default_permissions': ('admin', 'create', 'delete', 'update', 'view'),
            },
        ),
    ]
