# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_0_8_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sls_path', models.CharField(max_length=128, verbose_name='SLS Path')),
                ('host', models.CharField(max_length=256, verbose_name='Host')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='queued', max_length=32, verbose_name='Status')),
                ('health', models.CharField(choices=[('healthy', 'healthy'), ('unhealthy', 'unhealthy')], default='unknown', max_length=32, verbose_name='Health')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='environment',
            name='orchestrate_sls_path',
            field=models.CharField(default='orchestrate', max_length=255, verbose_name='Orchestrate SLS Path'),
        ),
        migrations.AddField(
            model_name='componentmetadata',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_metadatas', to='environments.Environment'),
        ),
    ]
