# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:35
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_0_8_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='status',
            field=model_utils.fields.StatusField(default=b'error', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
