# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_0_8_0_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprintaccessrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blueprintaccessrule',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blueprintaccessrule',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blueprintvolume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blueprintvolume',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blueprintvolume',
            name='title',
        ),
    ]
