# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_0_8_0_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprinthostdefinition',
            name='slug',
        ),
    ]
