# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_0_8_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudaccount',
            name='account_id',
        ),
    ]
