# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_0_8_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='account_id',
            field=models.CharField(default='INVALID_ACCOUNT_ID', max_length=64, verbose_name='Account ID'),
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='size_in_gb',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='size_in_gb',
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='cloudimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cloudimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='cloudinstancesize',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_sizes', to='cloud.CloudProvider', verbose_name='Cloud Provider'),
        ),
        migrations.AlterField(
            model_name='cloudregion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cloud.CloudProvider', verbose_name='Cloud Provider'),
        ),
        migrations.AlterField(
            model_name='cloudzone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='cloud.CloudRegion', verbose_name='Cloud Region'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='filesystem_type',
            field=models.CharField(choices=[('ext2', 'ext2'), ('ext3', 'ext3'), ('ext4', 'ext4'), ('fuse', 'fuse'), ('xfs', 'xfs')], max_length=16, verbose_name='Filesystem Type'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_id',
            field=models.CharField(max_length=32, verbose_name='Snapshot ID'),
        ),
    ]
