# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_0_8_0_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudaccount',
            name='config_file',
        ),
        migrations.RemoveField(
            model_name='cloudimage',
            name='config_file',
        ),
        # Then delete the props_file field after we loaded data from it in the previous migration
        migrations.RemoveField(
            model_name='cloudaccount',
            name='global_orch_props_file',
        ),
    ]
