# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_0_8_0_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygroup',
            name='group_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_id',
            field=models.CharField(max_length=64, verbose_name='Snapshot ID'),
        ),
    ]
